const bestSeasons = {
  France: "May to September",
  Spain: "April to June and September to October",
  "United States": "April to June and September to October",
  China: "April to May and September to October",
  Italy: "April to June and September to October",
  Turkey: "April to June and September to November",
  Mexico: "November to April",
  Thailand: "November to February (cool and dry)",
  Germany: "May to September",
  "United Kingdom": "June to September",
  Austria: "May to September or December for skiing",
  Russia: "May to September",
  Greece: "April to June and September to October",
  Portugal: "May to September",
  Netherlands: "April to October",
  Morocco: "March to May and September to November",
  India: "October to March",
  Japan: "March to May and October to November",
  Macao: "October to December",
  "Hong Kong": "October to December",
  "United Arab Emirates": "November to March",
  Canada: "June to September",
  Poland: "May to September",
  Switzerland: "June to September or December to February (ski)",
  Sweden: "June to August",
  Malaysia: "May to September (west coast), December to February (east coast)",
  Egypt: "October to April",
  Belgium: "May to September",
  Australia: "September to November and March to May",
  Vietnam: "March to May and September to November",
  "Czech Republic": "May to September",
  Hungary: "May to September",
  "South Africa": "May to September (safari), November to March (coast)",
  Ireland: "May to September",
  Croatia: "May to September",
  Iceland: "June to August",
  Denmark: "May to September",
  Norway: "June to August",
  Finland: "June to August",
  Belarus: "May to September",
  Cuba: "November to April",
  Brazil: "May to October (dry season)",
  Chile: "September to November and March to May",
  Indonesia: "May to September",
  "Dominican Republic": "December to April",
  Tunisia: "March to May and September to November",
  Kenya: "June to October and January to February",
  Qatar: "November to March",
};
const culturalTips = {
  France: "Greet shopkeepers with 'Bonjour'. Tipping is appreciated but not obligatory.",
  Spain: "Late meals are common. Respect siesta times and be punctual.",
  "United States": "Tipping is expected (15–20%). Respect personal space.",
  China: "Avoid political discussions. Gifts are refused before accepted.",
  Italy: "Dress modestly in churches. Punctuality is flexible in social settings.",
  Turkey: "Remove shoes indoors. Hospitality is a key part of culture.",
  Mexico: "Be friendly and informal. Avoid showing wealth in public.",
  Thailand: "Don’t touch heads. Respect the King and monks.",
  Germany: "Be punctual. Don’t cross streets on red. Quiet is valued.",
  "United Kingdom": "Queuing is important. Politeness and indirectness are cultural norms.",
  Austria: "Punctuality and formality are appreciated. Respect quiet hours.",
  Russia: "Give firm handshakes. Don’t smile too much at strangers.",
  Greece: "Expect relaxed pace. Use hand gestures carefully.",
  Portugal: "Speak quietly in public. Modest dress in religious sites.",
  Netherlands: "Be direct but polite. Don’t confuse honesty with rudeness.",
  Morocco: "Dress conservatively. Always ask before taking photos.",
  India: "Remove shoes before entering homes. Avoid public affection.",
  Japan: "Don’t tip. Be quiet in public transport. Bow for greeting.",
  Macao: "Mix of Chinese and Portuguese etiquette. Gambling is legal and part of tourism.",
  "Hong Kong": "Tipping is common. Respect elders and avoid political topics.",
  "United Arab Emirates": "Dress conservatively. Friday is a holy day.",
  Canada: "Tipping is expected. Politeness and tolerance are cultural values.",
  Poland: "Shake hands firmly. Avoid public criticism.",
  Switzerland: "Punctuality is key. Respect silence and privacy.",
  Sweden: "Don’t boast. Silence is respected. Queue patiently.",
  Malaysia: "Remove shoes indoors. Use right hand for eating/giving.",
  Egypt: "Dress modestly. Friday is for prayer. Don’t discuss religion.",
  Belgium: "Punctuality and manners matter. Don’t chew gum in meetings.",
  Australia: "Very informal. Tipping not expected. Be friendly.",
  Vietnam: "Don’t point with feet. Remove shoes indoors.",
  "Czech Republic": "Punctuality matters. Be reserved at first.",
  Hungary: "Toast with eye contact. Don’t clink beer glasses (historical reason).",
  "South Africa": "Don’t display valuables. Tipping is standard in services.",
  Ireland: "Be modest and friendly. Tipping is appreciated.",
  Croatia: "Respect family traditions. Dress smart in towns.",
  Iceland: "Very safe. Don’t tip. Be environmentally conscious.",
  Denmark: "Punctuality is crucial. Modesty and equality are valued.",
  Norway: "Don’t talk loudly. Remove shoes indoors.",
  Finland: "Silence is not awkward. Don’t interrupt others.",
  Belarus: "Respect authority. Be formal in speech and dress.",
  Cuba: "Be patient with bureaucracy. Bring cash instead of cards.",
  Brazil: "Be informal and warm. Avoid flashy clothing in public.",
  Chile: "Avoid politics. Punctuality varies by region.",
  Indonesia: "Use right hand. Dress modestly, especially in temples.",
  "Dominican Republic": "Be relaxed. Tipping is expected in resorts.",
  Tunisia: "Dress modestly. Avoid public affection.",
  Kenya: "Greet with respect. Use right hand for giving items.",
  Qatar: "No alcohol in public. Dress conservatively, especially women."
};
